version: '3.4'

services:
  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "DbP@ssword!"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PDbP@ssword!", "-Q", "select 1"]
      interval: 2s
      retries: 60

  productweb:
    image: ${DOCKER_REGISTRY-}productweb
    environment:
      - NODE_ENV=development
    build: 
      context: ../productweb
      dockerfile: ../productweb/Dockerfile
      target: development
    ports: 
      - 3000:3000
    depends_on:
      productapi:
        condition: service_started